<?php
/**
 * Implementation of hook_menu().
 */
function gn_theme_includes_menu() {
	$items["gn_theme_includes/%"] = array(
  	'page callback' => '_gn_theme',
  	'access callback' => TRUE,
  	'type' => MENU_CALLBACK,
	);
	$items["theme/header"] = array(
  	'page callback' => '_gn_theme_theme_header',
  	'access callback' => TRUE,
  	'type' => MENU_CALLBACK,
	);
	$items["theme/footer"] = array(
  	'page callback' => '_gn_theme_theme_footer',
  	'access callback' => TRUE,
  	'type' => MENU_CALLBACK,
	);
	return $items;
}
/**
 * Implementation of hook_theme().
 */
function gn_theme_includes_theme($existing, $type, $theme, $path) {
	$themes = array(
    'theme_header' => array(
      'arguments' => array('vars'=>NULL),
      'template' => 'theme_header',
    ),
    'theme_footer' => array(
      'arguments' => array('vars'=>NULL),
      'template' => 'theme_footer',
    ),
  );
  return $themes;
}

/**
 * Implementation of hook_preprocess_NAME().
 *
 */
function gn_theme_includes_preprocess_page(&$variables) {
	if($_GET['q'] == 'theme/header' || $_GET['q'] == 'theme/footer'){

	}elseif($_GET['q'] == 'gn_theme_includes/page'){
		$variables['template_files'][] = 'theme_bookingengine';
		$variables['theme_header'] = theme('theme_header', $variables);
		$variables['theme_footer'] = theme('theme_footer', $variables);
		$variables['theme_header'] = _gn_theme_includes_replacerelativebyabsolute($variables['theme_header']);
		$variables['theme_footer'] = _gn_theme_includes_replacerelativebyabsolute($variables['theme_footer']);
	}else{
		$variables['theme_header'] = theme('theme_header', $variables);
		$variables['theme_footer'] = theme('theme_footer', $variables);
	}
}

/**
 * Implementation of hook_theme_registry_alter().
 *
 * Make gn_theme's page preprocess function run *after* everything else's,
 * so that a theme can't call other variables and mess everything up.
 */
function gn_theme_includes_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['page'])) {
    if (count($theme_registry['page']['preprocess functions']) > 0) {
      // If jquery_update's preprocess function is there already, remove it.
      if ($key = array_search('gn_theme_includes_preprocess_page', $theme_registry['page']['preprocess functions'])) {
        unset($theme_registry['page']['preprocess functions'][$key]);
      }
    }
    // Now tack it on at the end so it runs after everything else.
    $theme_registry['page']['preprocess functions'][] = 'gn_theme_includes_preprocess_page';
  }
}

/**
 * Implementation of hook_preprocess_NAME().
 *
 */
function gn_theme_includes_preprocess_theme_header(&$variables, $othervars) {
	$vars = $variables;
	$variables = array_merge($vars, $vars['vars']);
	$variables['template_files'][] = 'theme_header';
}

/**
 * Implementation of hook_preprocess_NAME().
 *
 */
function gn_theme_includes_preprocess_theme_footer(&$variables, $othervars) {
	$vars = $variables;
	$variables = array_merge($vars, $vars['vars']);
	$variables['template_files'][] = 'theme_footer';
}

function _gn_theme_theme_header(){
	print theme('page');
}

function _gn_theme(){
	print theme('page');
}

function _gn_theme_theme_footer(){
	print theme('page');
}

function _gn_theme_includes_replacerelativebyabsolute($valeur){
	$new_valeur = str_replace('href="/', 'href="http://' . $_SERVER['HTTP_HOST'] . '/', $valeur);
	return $new_valeur;
}